panikdb/aa/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('members/', views.members_list_view, name='members-list-view'),
    path('members/new/', views.member_new, name='member-new'),
    path('members/vcard/', views.members_vcard, name='members-vcard'),
    path('members/csv/', views.members_csv, name='members-csv'),
    path('members/<int:pk>/', views.member_view, name='member-view'),
    path('members/<int:pk>/edit/', views.member_edit, name='member-edit'),
    path('members/<int:pk>/emissions/', views.member_emissions, name='member-emissions'),
    path(
        'members/<int:pk>/emissions/remove/<int:em_pk>/',
        views.member_emission_remove,
        name='member-emission-remove',
    ),
    path('members/<int:pk>/mark-as-active/', views.mark_as_active, name='member-mark-as-active'),
    path('members/<int:pk>/mark-as-inactive/', views.mark_as_inactive, name='member-mark-as-inactive'),
    path('members/<int:pk>/password/', views.member_password, name='member-password'),
    path(
        'members/<int:pk>/register-membership/',
        views.register_membership,
        name='member-register-membership',
    ),
    path('members/groups/', views.groups_list, name='groups-list'),
    path('members/groups/new/', views.group_new, name='group-new'),
    path('members/groups/<int:pk>/', views.group_view, name='group-view'),
    path('members/groups/<int:pk>/perms/', views.group_update_perms, name='group-update-perms'),
    path('members/groups/<int:pk>/delete/', views.group_delete, name='group-delete'),
    path('profile/', views.profile_view, name='profile-view'),
    path('profile/edit/', views.profile_contact_edit, name='profile-contact-edit'),
]

panikdb/oauth/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('authorize', views.authorize, name='oauth-authorize'),
    path('jwks', views.jwks, name='oauth-jwks'),
    path('token', views.token, name='oauth-token'),
    path('user-info', views.user_info, name='oauth-user-info'),
]

panikdb/pige/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('download/', views.download, name='pige-download-post'),
    path('download/pending/<int:object_id>/', views.download_pending),
    re_path(r'^download/(?P<spec>[\w\d\.-]+)$', views.download_spec, name='pige-download-spec'),
]

panikdb/urls.py
import combo.public.views
from agendas.urls import urlpatterns as agendas_urlpatterns
from ckeditor.views import browse as ckeditor_browse
from ckeditor.views import upload as ckeditor_upload
from combo.manager.urls import urlpatterns as combo_manager_urls
from combo.public.views import snapshot as combo_snapshot_view
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic import RedirectView
from emissions.models import Emission, Episode, NewsItem
from emissions.urls import urlpatterns as emissions_urlpatterns
from matos.urls import urlpatterns as matos_urlpatterns
from newsletter.urls import management_patterns as newsletter_urlpatterns
from nonstop.urls import public_urlpatterns as nonstop_public_urlpatterns
from nonstop.urls import urlpatterns as nonstop_urlpatterns
from panikombo.urls import urlpatterns as panikombo_urlpatterns
from wiki.urls import urlpatterns as wiki_urlpatterns

from . import views
from .aa.urls import urlpatterns as aa_urlpatterns
from .forms import AuthenticationForm
from .oauth.urls import urlpatterns as oauth_urlpatterns
from .oauth.views import well_known_openid_configuration
from .pige.urls import urlpatterns as pige_urlpatterns
from .poll import views as poll_views
from .regie.urls import urlpatterns as regie_urlpatterns
from .service_messages.urls import urlpatterns as service_messages_urlpatterns
from .urls_utils import cms_permission_required, decorated_includes

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^ckeditor/upload/', login_required(ckeditor_upload)),
    re_path(r'^ckeditor/browse/', login_required(ckeditor_browse)),
    re_path(r'^search/', login_required(views.search), name='panikdb-search'),
    re_path(r'^emissions/', decorated_includes(login_required, include(emissions_urlpatterns))),
    re_path(r'^matos/', decorated_includes(login_required, include(matos_urlpatterns))),
    re_path(r'^nonstop/', decorated_includes(login_required, include(nonstop_urlpatterns))),
    path('nonstop/', include(nonstop_public_urlpatterns)),
    path('newsletters/add', views.newsletter_create, name='newsletter-create'),
    re_path(r'^newsletters/', decorated_includes(login_required, include(newsletter_urlpatterns))),
    re_path(r'^cms/', decorated_includes(cms_permission_required, include(combo_manager_urls))),
    re_path(
        r'^cms-snapshot/(?P<pk>\w+)/$',
        cms_permission_required(combo_snapshot_view),
        name='combo-snapshot-view',
    ),
    re_path(r'^focus/set/(?P<object_type>[\w,-]+)/(?P<object_id>\d+)$', views.focus_set, name='focus-set'),
    re_path(
        r'^focus/unset/(?P<object_type>[\w,-]+)/(?P<object_id>\d+)$', views.focus_unset, name='focus-unset'
    ),
    path(
        'accounts/login/',
        auth_views.LoginView.as_view(authentication_form=AuthenticationForm),
        name='login',
    ),
    re_path(r'^accounts/logout/', auth_views.logout_then_login, name='logout'),
    path(
        'password/change/',
        auth_views.PasswordChangeView.as_view(),
        name='password_change',
    ),
    path(
        'password/change/done/',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done',
    ),
    path(
        'accounts/password_reset/',
        auth_views.PasswordResetView.as_view(
            email_template_name='registration/password_reset_email.html',
        ),
        name='password_reset',
    ),
    path(
        'accounts/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'accounts/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'
    ),
    path('vote/', poll_views.vote, name='vote'),
    path('vote/results/', poll_views.vote_results, name='vote-results'),
    re_path(
        r'^ajax/cell/(?P<page_pk>\d+)/(?P<cell_reference>[\w_]+-\d+)/$',
        combo.public.views.ajax_page_cell,
        name='combo-public-ajax-page-cell',
    ),
    re_path(r'^agendas/', decorated_includes(login_required, include(agendas_urlpatterns))),
    path('panikombo/', include(panikombo_urlpatterns)),
    path('wiki/', include(wiki_urlpatterns)),
    path('pige/', include(pige_urlpatterns)),
    path('regie/', include(regie_urlpatterns)),
    path('oauth/', include(oauth_urlpatterns)),
    re_path(r'^\.well-known/openid-configuration$', well_known_openid_configuration),
    path('messages/', include(service_messages_urlpatterns)),
    path('system/', views.system),
    re_path(r'^admin/', admin.site.urls),
]

urlpatterns += aa_urlpatterns

from combo import plugins

urlpatterns = plugins.register_plugins_urls(urlpatterns)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += staticfiles_urlpatterns()

from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

panikdb/aa/models.py
import re

from django.contrib.auth.models import AbstractUser
from django.core import validators
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from emissions.models import Emission, Episode, NewsCategory, NewsItem, SoundFile


class User(AbstractUser):
    emissions = models.ManyToManyField(Emission, blank=True)
    news_categories = models.ManyToManyField(NewsCategory, blank=True)

    phone = models.CharField(_('Phone'), max_length=20, null=True, blank=True)
    mobile = models.CharField(_('Mobile'), max_length=20, null=True, blank=True)
    share_contact_details = models.BooleanField(_('Share contact detais with members'), default=True)

    class Meta:
        ordering = ['first_name', 'last_name']

    def can_manage(self, object):
        if self.is_staff:
            return True
        if isinstance(object, Emission):
            return self.has_perm('emissions.change_emission') or object in self.emissions.all()
        if isinstance(object, Episode):
            return self.has_perm('emissions.change_episode') or object.emission in self.emissions.all()
        if isinstance(object, SoundFile):
            return (
                self.has_perm('emissions.change_soundfile') or object.episode.emission in self.emissions.all()
            )
        if isinstance(object, NewsItem):
            return self.has_perm('emissions.change_newsitem') or object.emission in self.emissions.all()
        return False

    def active_emissions(self):
        # list comprehension to act on prefetched emissions
        return [x for x in self.emissions.all() if not x.archived]

    def is_ca(self):
        return bool(any(x for x in self.groups.all() if x.name == 'CA'))

    def is_cp(self):
        return bool(any(x for x in self.groups.all() if x.name == 'CP'))

    def has_current_membership(self):
        current_year = now().year
        return self.membership_set.filter(year=current_year).exists()

    def __str__(self):
        s = super().__str__()
        parts = []
        if self.first_name:
            parts.append(self.first_name)
        if self.last_name:
            parts.append(self.last_name)
        if parts:
            s = ' '.join(parts)
        return s


class Membership(models.Model):
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    year = models.IntegerField(_('Year'))
    creation_timestamp = models.DateTimeField(auto_now_add=True)
    payment_date = models.DateField(verbose_name=_('Date'), blank=True, null=True)
    payment_amount = models.DecimalField(
        verbose_name=_('Amount'), decimal_places=2, max_digits=6, blank=True, null=True
    )
    notes = models.TextField(_('Notes'), blank=True, null=True)

panikdb/mastodon/models.py
from django.db import models
from emissions.models import Episode, NewsItem


class MastodonSettings(models.Model):
    base_url = models.CharField(max_length=255)
    client_id = models.CharField(max_length=255)
    client_secret = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)

    @classmethod
    def singleton(cls):
        return cls.objects.all().first() or cls()

    def configured(self):
        return bool(
            self.base_url and self.client_id and self.client_secret and self.username and self.password
        )


class MastodonEntry(models.Model):
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE, null=True)
    newsitem = models.ForeignKey(NewsItem, on_delete=models.CASCADE, null=True)
    creation_timestamp = models.DateTimeField(auto_now_add=True)

    status_id = models.CharField(max_length=255, null=True)

panikdb/oauth/views.py
import base64
import datetime
import random

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, HttpResponseNotAllowed, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now
from django.views.decorators.csrf import csrf_exempt
from jwcrypto.jwk import JWK
from jwcrypto.jwt import JWT

from .models import OAuthAccessToken, OAuthClient, OAuthCode, OAuthSub


@login_required
def authorize(request, *args, **kwargs):
    state = request.GET['state']
    client = OAuthClient.objects.get(client_id=request.GET['client_id'])
    code = OAuthCode.objects.create(client=client, user=request.user, nonce=request.GET.get('nonce'))
    redirect_uri = request.GET['redirect_uri']
    params = {
        'code': code.code,
        'state': state,
    }
    if request.GET.get('nonce'):
        params['nonce'] = request.GET.get('nonce')
    return HttpResponseRedirect(redirect_uri + '?%s' % '&'.join(['%s=%s' % x for x in params.items()]))


@csrf_exempt
def token(request, *args, **kwargs):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    try:
        code = OAuthCode.objects.get(code=request.POST.get('code'))
    except OAuthCode.DoesNotExist:
        return HttpResponseForbidden()

    start = now()
    exp = start + datetime.timedelta(seconds=30)

    sub, created = OAuthSub.objects.get_or_create(client=code.client, user=code.user)

    id_token = {
        'iss': request.build_absolute_uri('/'),
        'aud': code.client.client_id,
        'sub': str(sub.sub),
        'exp': int(exp.timestamp()),
        'iat': int(start.timestamp()),
        'auth_time': int(start.timestamp()),
        'acr': '0',
    }
    if code.nonce:
        id_token['nonce'] = code.nonce
    header = {'alg': 'HS256'}
    k = base64.urlsafe_b64encode(code.client.client_secret.encode('utf-8')).strip(b'=')
    jwk = JWK(kty='oct', k=k.decode())
    jwt = JWT(header=header, claims=id_token)
    jwt.make_signed_token(jwk)

    access_token = OAuthAccessToken.objects.create(client=code.client, user=code.user)

    response = {
        'access_token': access_token.token,
        'token_type': 'Bearer',
        'expires_in': 30,
        'id_token': jwt.serialize(),
        'refresh_token': None,
    }

    return JsonResponse(response)


def user_info(request, *args, **kwargs):
    try:
        authorization = request.headers['authorization'].split()
    except KeyError:
        return HttpResponseForbidden('missing authorization header')
    if len(authorization) != 2 or authorization[0] != 'Bearer':
        return HttpResponseForbidden('invalid authorization header')
    try:
        access_token = OAuthAccessToken.objects.get(token=authorization[1])
    except OAuthAccessToken.DoesNotExist:
        return HttpResponseForbidden('missing access token')

    sub = OAuthSub.objects.get(client=access_token.client, user=access_token.user)

    user_info = {
        # use a random string as id, as it is required for pharum not to pick
        # an existing and wrong user.
        'id': str(random.randint(10**6, 10**7)),
        'email': access_token.user.email,
        'name': str(access_token.user),
        'username': slugify(str(access_token.user)),
        'sub': sub.sub,
    }
    return JsonResponse(user_info)


def jwks(request):
    return JsonResponse({'keys': []})


def well_known_openid_configuration(request):
    data = {
        'issuer': request.build_absolute_uri('/'),
        'authorization_endpoint': request.build_absolute_uri(reverse('oauth-authorize')),
        'token_endpoint': request.build_absolute_uri(reverse('oauth-token')),
        'jwks_uri': request.build_absolute_uri(reverse('oauth-jwks')),
        'userinfo_endpoint': request.build_absolute_uri(reverse('oauth-user-info')),
        'token_endpoint_auth_methods_supported': ['client_secret_post'],
    }
    return JsonResponse(data)

panikdb/poll/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from .models import Vote


class VoteView(TemplateView):
    template_name = 'vote.html'

    def dispatch(self, request, *args, **kwargs):
        return redirect('home')
        try:
            vote = Vote.objects.get(user=request.user)
            messages.error(request, 'Non !')
            return redirect('home')
        except Vote.DoesNotExist:
            pass
        return super().dispatch(request, *args, **kwargs)

    def post(self, request):
        choice = request.POST['choice']
        comment = request.POST['comment']

        vote = Vote(user=request.user, choice=request.POST['choice'], comment=request.POST['comment'])
        vote.save()
        messages.success(request, 'Merci !')
        return redirect('home')


vote = login_required(VoteView.as_view())


class ResultsView(ListView):
    model = Vote
    template_name = 'vote_results.html'

    def get_queryset(self):
        return Vote.objects.order_by('?')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['choice_1'] = self.get_queryset().filter(choice="1").count()
        context['choice_2'] = self.get_queryset().filter(choice="2").count()
        context['choice_3'] = self.get_queryset().filter(choice="3").count()
        return context


vote_results = login_required(ResultsView.as_view())

panikdb/service_messages/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.views.generic.edit import UpdateView

from .models import Message


class MessageEditView(UpdateView):
    model = Message
    fields = ['style', 'text']
    success_url = '/'
    template_name = 'service_message_form.html'

    def dispatch(self, *args, **kwargs):
        if not self.request.user.has_perm('service_messages.change_message'):
            raise PermissionDenied()
        return super().dispatch(*args, **kwargs)


message_edit = login_required(MessageEditView.as_view())

panikdb/templates/aa/group_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{{ object }}</h2>
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <p>
      {% trans "Are you sure you want to delete this group?" %}
    </p>
    <div class="buttons">
      <button class="delete-button">{% trans "Confirm Deletion" %}</button>
      <a class="cancel" href="..">{% trans "Cancel" %}</a>
    </div>
{% endblock %}

panikdb/templates/aa/group_detail.html
{% extends "aa/groups_list.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% trans "Permissions" %}</h2>
{% endblock %}

{% block content %}
  <form method="POST" action="{% url 'group-update-perms' pk=group.id %}">
    {% csrf_token %}
    <ul>
      {% for perm in perms %}
        <li><label><input name="perms" type="checkbox" value="{{ perm.code }}" {% if perm.enabled %}checked{% endif %}>{{ perm.label }}</label></li>
      {% endfor %}
    </ul>
    <div class="buttons">
      <button type="submit">{% trans "Update" %}</button>
    </div>
  </form>

{% endblock %}

panikdb/templates/aa/group_new.html
{% extends "base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% trans "New group" %}</h2>
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="buttons">
      <button>{% trans "Add" %}</button>
      <a class="cancel" href="..">{% trans "Cancel" %}</a>
    </div>
{% endblock %}

panikdb/templates/aa/groups_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Groups" %} | {% trans "Members" %} | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>{% trans "Groups" %}</h2>
  {% if perms.aa.add_user %}
    <span class="actions">
      <a rel="popup" href="{% url 'group-new' %}">{% trans 'Add new group' %}</a>
    </span>
  {% endif %}
{% endblock %}

{% block more-user-links %}{{ block.super }} <a class="button icon-members" href="{% url 'members-list-view' %}">Annuaire des membres</a>{% endblock %}

{% block content %}
  <ul class="objects-list single-links layers">
    {% for group in object_list %}
      <li><a rel="popup" href="{% url 'group-view' pk=group.id %}">{{ group }}</a>
        <a class="delete" rel="popup" href="{% url 'group-delete' pk=group.id %}">{% trans "remove" %}</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

panikdb/templates/aa/member_emissions.html
{% extends "aa/user_list.html" %}
{% load i18n %}

{% block appbar %}
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {% if user.emissions %}
      <ul class="objects-list single-links layers">
        {% for emission in member.emissions.all %}
          <li><a>{{ emission.title }}</a>
            <a class="delete" href="{% url 'member-emission-remove' pk=member.id em_pk=emission.pk %}">{% trans "remove" %}</a></li>
        {% endfor %}
      </ul>
    {% endif %}

    {{ form.as_p }}

    <div class="buttons">
      <a class="cancel" href="{% url 'member-view' pk=member.id %}">Annuler</a>
      <button>Ajouter l’émission</button>
    </div>
  </form>
{% endblock %}

panikdb/templates/aa/member_password.html
{% extends "aa/user_list.html" %}
{% load gadjo i18n %}

{% block appbar %}
  <h2>{% trans "Password Change" %}</h2>
{% endblock %}

{% block content %}
  <form id="admin-password-change-form" method="post" class="pk-mark-optional-fields">
    {% csrf_token %}
    {{ form|with_template }}

    <div class="buttons">
      <button>{% trans "Save" %}</button>
      <a class="cancel" href="{% url 'member-view' pk=user_pk %}">{% trans "Cancel" %}</a>
    </div>
  </form>
{% endblock %}

panikdb/templates/aa/profile.html
{% extends "base.html" %}

{% block appbar %}
  <h2>{{ user }}</h2>
{% endblock %}

{% block content %}
  <div class="section">
    <h3>Informations de contact</h3>
    <div>
      <ul class="contact-details">
        <li>Email : {{ user.email }}</li>
        <li>Téléphone : {{ user.mobile|default_if_none:"" }} {% if user.phone %}— {{ user.phone }} (fixe){% endif %}</li>
      </ul>
      <a class="button" data-popup href="{% url 'profile-contact-edit' %}">Modifier</a>
    </div>
  </div>

  <div class="section padded">
    <a class="button" data-popup href="{% url 'password_change' %}">Changement de mot de passe</a>
  </div>

{% endblock %}

panikdb/templates/aa/profile_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="buttons">
      <button>{% trans "Save" %}</button>
      <a class="cancel" href="../..">{% trans "Cancel" %}</a>
    </div>
  </form>
{% endblock %}

panikdb/templates/aa/register_membership.html
{% extends "aa/user_list.html" %}
{% load i18n %}

{% block appbar %}
{% endblock %}

{% block content %}
  <form method="post" class="register-membership-form">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="buttons">
      <a class="cancel" href="{% url 'member-view' pk=member.id %}">Annuler</a>
      <button>Valider</button>
    </div>
  </form>
{% endblock %}

panikdb/templates/aa/user_detail.html
{% extends "aa/user_list.html" %}
{% load i18n %}

{% block page-title %}{{ user }} | {% trans "Members" %} | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>{{ user }}</h2>
{% endblock %}

{% block content %}
  <div class="section">
    <h3>Informations</h3>
    <div>
      {% if not user.is_active %}<p>Personne marquée inactive.</p>{% endif %}
      {% if user.active_emissions %}
        <p>{{ user.active_emissions|join:", " }}.</p>
      {% endif %}
      {% if user.is_ca %}<p>Membre du CA.</p>{% endif %}
      {% if user.is_cp %}<p>Membre du CP.</p>{% endif %}
      {% if perms.aa.add_user or user.share_contact_details %}
        <ul class="contact-details">
          <li>Email : {{ user.email }}</li>
          <li>Téléphone : {{ user.mobile|default_if_none:"" }} {% if user.phone %}— {{ user.phone }} (fixe){% endif %}</li>
        </ul>
      {% endif %}
      {% if perms.aa.add_user %}
        <a class="button" data-popup href="{% url 'member-edit' pk=user.id %}">Modifier</a>
        <a class="button" data-popup href="{% url 'member-password' pk=user.id %}">Modifier le mot de passe</a>
        {% if user.is_active %}
          <a class="button" href="{% url 'member-mark-as-inactive' pk=user.id %}">Marquer comme inactive</a>
        {% else %}
          <a class="button" href="{% url 'member-mark-as-active' pk=user.id %}">Marquer comme active</a>
        {% endif %}
        <a class="button" data-popup href="{% url 'member-emissions' pk=user.id %}">Émissions</a>
      {% endif %}
    </div>
  </div>

  {% if has_membership_support and perms.emissions.add_membership %}
    <div class="section">
      <h3>Cotisations</h3>
      <div>
        {% if current_membership %}
          <p>En ordre de cotisation.
            {% if current_membership.payment_date and current_membership.payment_amount %}
              ({{ current_membership.payment_amount }}€ payés le {{ current_membership.payment_date }})
            {% endif %}
          </p>
          {% if current_membership.notes %}<p>{{ current_membership.notes }}</p>{% endif %}
        {% else %}
          <p>Pas en ordre de cotisation pour cette année.</p>
          <a rel="popup" class="button" href="{% url 'member-register-membership' pk=user.id %}">Enregistrer la cotisation</a>
        {% endif %}
        {% if past_memberships %}
          <p>Années précédentes :</p>
          <ul>
            {% for membership in past_memberships %}
              <li>{{ membership.year }} {% if membership.payment_date and membership.payment_amount %}
                ({{ membership.payment_amount }}€ payés le {{ membership.payment_date }}){% endif %}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
    </div>
  {% endif %}
{% endblock %}

panikdb/templates/aa/user_form.html
{% extends "aa/user_list.html" %}
{% load gadjo i18n %}

{% block appbar %}
  {% if object.id %}
  {% else %}
    <h2>{% trans "New member" %}</h2>
  {% endif %}
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|with_template }}

    <div class="buttons">
      <button>{% trans "Save" %}</button>
      {% if object.id %}
        <a class="cancel" href="{% url 'member-view' pk=object.id %}">{% trans "Cancel" %}</a>
      {% else %}
        <a class="cancel" href="{% url 'members-list-view' %}">{% trans "Cancel" %}</a>
      {% endif %}
    </div>
  </form>
{% endblock %}

panikdb/templates/aa/user_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Members" %} | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>{% trans "Members" %}</h2>
  {% if perms.aa.add_user %}
    <span class="actions">
      <a href="{% url 'groups-list' %}">{% trans 'Manage groups' %}</a>
      <a rel="popup" href="{% url 'member-new' %}">{% trans 'Add new member' %}</a>
    </span>
  {% endif %}
{% endblock %}

{% block more-user-links %}{{ block.super }} <a class="button icon-members" href="{% url 'members-list-view' %}">Annuaire des membres</a>{% endblock %}

{% block content %}
  <div class="section padded members-filter">
    <form>
      <input name="q" type="search" value="{{ request.GET.q }}"> <button>{% trans 'Search' %}</button>
    </form>
    {% if has_membership_support and perms.emissions.add_membership %}
      <a class="button" href="?membership=ok">En ordre de cotisation</a>
      <a class="button" href="?membership=renew">Cotisations à renouveler</a>
    {% endif %}
  </div>

  <table class="main">
    {% for user in object_list %}
      <tr>
        <td><a href="{% url 'member-view' pk=user.id %}">{{ user }}</a>
          {% if not user.is_active %}(inactif){% endif %}
        </td>
        <td>{% if user.is_ca %}CA{% endif %}
          {% if user.is_cp %}CP{% endif %}</td>
        <td>{{ user.active_emissions|join:", " }}</td>
        <td>{% if user.share_contact_details and user.email %}<a href="mailto:{{ user.email }}">{{ user.email }}</a>{% endif %}</td>
        <td>{% if user.share_contact_details %}{{ user.phone|default:"" }} {{ user.mobile|default:"" }}{% endif %}</td>
      </tr>
    {% endfor %}
  </table>

  <div class="members-pagination">
    {% include "gadjo/pagination.html" %}
    {% if not request.GET.membership %}
      <p>
        <a class="button" href="{% url 'members-vcard' %}?q={{ request.GET.q }}" download="members.vcf">{% trans "vCard" %}</a>
        <a class="button" href="{% url 'members-csv' %}?q={{ request.GET.q }}" download="members.csv">{% trans "CSV" %}</a>
      </p>
    {% endif %}
  </div>

  {% if total_membership and has_membership_support and perms.emissions.add_membership %}
    <div class="section">
      <div>Total des cotisations : {{total_money}} €</div>
    </div>
  {% endif %}

{% endblock %}