panikdb/aa/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('members/', views.members_list_view, name='members-list-view'),
    path('members/new/', views.member_new, name='member-new'),
    path('members/vcard/', views.members_vcard, name='members-vcard'),
    path('members/csv/', views.members_csv, name='members-csv'),
    path('members/<int:pk>/', views.member_view, name='member-view'),
    path('members/<int:pk>/edit/', views.member_edit, name='member-edit'),
    path('members/<int:pk>/emissions/', views.member_emissions, name='member-emissions'),
    path(
        'members/<int:pk>/emissions/remove/<int:em_pk>/',
        views.member_emission_remove,
        name='member-emission-remove',
    ),
    path('members/<int:pk>/mark-as-active/', views.mark_as_active, name='member-mark-as-active'),
    path('members/<int:pk>/mark-as-inactive/', views.mark_as_inactive, name='member-mark-as-inactive'),
    path('members/<int:pk>/password/', views.member_password, name='member-password'),
    path(
        'members/<int:pk>/register-membership/',
        views.register_membership,
        name='member-register-membership',
    ),
    path('members/groups/', views.groups_list, name='groups-list'),
    path('members/groups/new/', views.group_new, name='group-new'),
    path('members/groups/<int:pk>/', views.group_view, name='group-view'),
    path('members/groups/<int:pk>/perms/', views.group_update_perms, name='group-update-perms'),
    path('members/groups/<int:pk>/delete/', views.group_delete, name='group-delete'),
    path('profile/', views.profile_view, name='profile-view'),
    path('profile/edit/', views.profile_contact_edit, name='profile-contact-edit'),
]

panikdb/oauth/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('authorize', views.authorize, name='oauth-authorize'),
    path('jwks', views.jwks, name='oauth-jwks'),
    path('token', views.token, name='oauth-token'),
    path('user-info', views.user_info, name='oauth-user-info'),
]

panikdb/pige/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('download/', views.download, name='pige-download-post'),
    path('download/pending/<int:object_id>/', views.download_pending),
    re_path(r'^download/(?P<spec>[\w\d\.-]+)$', views.download_spec, name='pige-download-spec'),
]

panikdb/urls.py
import combo.public.views
from agendas.urls import urlpatterns as agendas_urlpatterns
from ckeditor.views import browse as ckeditor_browse
from ckeditor.views import upload as ckeditor_upload
from combo.manager.urls import urlpatterns as combo_manager_urls
from combo.public.views import snapshot as combo_snapshot_view
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic import RedirectView
from emissions.models import Emission, Episode, NewsItem
from emissions.urls import urlpatterns as emissions_urlpatterns
from matos.urls import urlpatterns as matos_urlpatterns
from newsletter.urls import management_patterns as newsletter_urlpatterns
from nonstop.urls import public_urlpatterns as nonstop_public_urlpatterns
from nonstop.urls import urlpatterns as nonstop_urlpatterns
from panikombo.urls import urlpatterns as panikombo_urlpatterns
from wiki.urls import urlpatterns as wiki_urlpatterns

from . import views
from .aa.urls import urlpatterns as aa_urlpatterns
from .forms import AuthenticationForm
from .oauth.urls import urlpatterns as oauth_urlpatterns
from .oauth.views import well_known_openid_configuration
from .pige.urls import urlpatterns as pige_urlpatterns
from .poll import views as poll_views
from .regie.urls import urlpatterns as regie_urlpatterns
from .service_messages.urls import urlpatterns as service_messages_urlpatterns
from .urls_utils import cms_permission_required, decorated_includes

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^ckeditor/upload/', login_required(ckeditor_upload)),
    re_path(r'^ckeditor/browse/', login_required(ckeditor_browse)),
    re_path(r'^search/', login_required(views.search), name='panikdb-search'),
    re_path(r'^emissions/', decorated_includes(login_required, include(emissions_urlpatterns))),
    re_path(r'^matos/', decorated_includes(login_required, include(matos_urlpatterns))),
    re_path(r'^nonstop/', decorated_includes(login_required, include(nonstop_urlpatterns))),
    path('nonstop/', include(nonstop_public_urlpatterns)),
    path('newsletters/add', views.newsletter_create, name='newsletter-create'),
    re_path(r'^newsletters/', decorated_includes(login_required, include(newsletter_urlpatterns))),
    re_path(r'^cms/', decorated_includes(cms_permission_required, include(combo_manager_urls))),
    re_path(
        r'^cms-snapshot/(?P<pk>\w+)/$',
        cms_permission_required(combo_snapshot_view),
        name='combo-snapshot-view',
    ),
    re_path(r'^focus/set/(?P<object_type>[\w,-]+)/(?P<object_id>\d+)$', views.focus_set, name='focus-set'),
    re_path(
        r'^focus/unset/(?P<object_type>[\w,-]+)/(?P<object_id>\d+)$', views.focus_unset, name='focus-unset'
    ),
    path(
        'accounts/login/',
        auth_views.LoginView.as_view(authentication_form=AuthenticationForm),
        name='login',
    ),
    re_path(r'^accounts/logout/', auth_views.logout_then_login, name='logout'),
    path(
        'password/change/',
        auth_views.PasswordChangeView.as_view(),
        name='password_change',
    ),
    path(
        'password/change/done/',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done',
    ),
    path(
        'accounts/password_reset/',
        auth_views.PasswordResetView.as_view(
            email_template_name='registration/password_reset_email.html',
        ),
        name='password_reset',
    ),
    path(
        'accounts/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'accounts/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'
    ),
    path('vote/', poll_views.vote, name='vote'),
    path('vote/results/', poll_views.vote_results, name='vote-results'),
    re_path(
        r'^ajax/cell/(?P<page_pk>\d+)/(?P<cell_reference>[\w_]+-\d+)/$',
        combo.public.views.ajax_page_cell,
        name='combo-public-ajax-page-cell',
    ),
    re_path(r'^agendas/', decorated_includes(login_required, include(agendas_urlpatterns))),
    path('panikombo/', include(panikombo_urlpatterns)),
    path('wiki/', include(wiki_urlpatterns)),
    path('pige/', include(pige_urlpatterns)),
    path('regie/', include(regie_urlpatterns)),
    path('oauth/', include(oauth_urlpatterns)),
    re_path(r'^\.well-known/openid-configuration$', well_known_openid_configuration),
    path('messages/', include(service_messages_urlpatterns)),
    path('system/', views.system),
    re_path(r'^admin/', admin.site.urls),
]

urlpatterns += aa_urlpatterns

from combo import plugins

urlpatterns = plugins.register_plugins_urls(urlpatterns)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += staticfiles_urlpatterns()

from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

panikdb/service_messages/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils.translation import gettext_lazy as _

MESSAGE_STYLES = (
    ('info', _('Info')),
    ('error', _('Alert')),
)


class Message(models.Model):
    style = models.CharField(_('Style'), max_length=20, default='info', choices=MESSAGE_STYLES)
    text = RichTextField(_('Description'), blank=True, default='')

panikdb/aa/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _

from .models import Membership, User


class MemberEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'mobile', 'groups']
        widgets = {
            'groups': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, hide_agenda=False, category=None, booking=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['groups'].queryset = self.fields['groups'].queryset.order_by('name')
        self.fields['groups'].help_text = None

    def clean_email(self):
        email = self.cleaned_data['email']
        if email and User.objects.exclude(pk=self.instance.id).filter(email=email).exists():
            raise ValidationError(_('This email is already used.'))
        return email


class MemberCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        widgets = {'password': forms.PasswordInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['email'].required = True
        self.fields['password'].required = False
        self.fields['password'].help_text = _('Can be left empty to get a random password generated.')

    def clean_email(self):
        email = self.cleaned_data['email']
        if email and User.objects.filter(email=email).exists():
            raise ValidationError(_('This email is already used.'))
        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        if not password:
            password = get_random_string(length=12)
        return password


def get_emissions_as_choices():
    from emissions.models import Emission

    return [(None, '')] + [(x.id, x.title) for x in Emission.objects.exclude(archived=True)]


class MemberEmissionForm(forms.Form):
    emission = forms.ChoiceField(label=_('New Emission'), required=True, choices=get_emissions_as_choices)


class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ['year', 'payment_date', 'payment_amount', 'notes']

panikdb/oauth/views.py
import base64
import datetime
import random

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, HttpResponseNotAllowed, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now
from django.views.decorators.csrf import csrf_exempt
from jwcrypto.jwk import JWK
from jwcrypto.jwt import JWT

from .models import OAuthAccessToken, OAuthClient, OAuthCode, OAuthSub


@login_required
def authorize(request, *args, **kwargs):
    state = request.GET['state']
    client = OAuthClient.objects.get(client_id=request.GET['client_id'])
    code = OAuthCode.objects.create(client=client, user=request.user, nonce=request.GET.get('nonce'))
    redirect_uri = request.GET['redirect_uri']
    params = {
        'code': code.code,
        'state': state,
    }
    if request.GET.get('nonce'):
        params['nonce'] = request.GET.get('nonce')
    return HttpResponseRedirect(redirect_uri + '?%s' % '&'.join(['%s=%s' % x for x in params.items()]))


@csrf_exempt
def token(request, *args, **kwargs):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    try:
        code = OAuthCode.objects.get(code=request.POST.get('code'))
    except OAuthCode.DoesNotExist:
        return HttpResponseForbidden()

    start = now()
    exp = start + datetime.timedelta(seconds=30)

    sub, created = OAuthSub.objects.get_or_create(client=code.client, user=code.user)

    id_token = {
        'iss': request.build_absolute_uri('/'),
        'aud': code.client.client_id,
        'sub': str(sub.sub),
        'exp': int(exp.timestamp()),
        'iat': int(start.timestamp()),
        'auth_time': int(start.timestamp()),
        'acr': '0',
    }
    if code.nonce:
        id_token['nonce'] = code.nonce
    header = {'alg': 'HS256'}
    k = base64.urlsafe_b64encode(code.client.client_secret.encode('utf-8')).strip(b'=')
    jwk = JWK(kty='oct', k=k.decode())
    jwt = JWT(header=header, claims=id_token)
    jwt.make_signed_token(jwk)

    access_token = OAuthAccessToken.objects.create(client=code.client, user=code.user)

    response = {
        'access_token': access_token.token,
        'token_type': 'Bearer',
        'expires_in': 30,
        'id_token': jwt.serialize(),
        'refresh_token': None,
    }

    return JsonResponse(response)


def user_info(request, *args, **kwargs):
    try:
        authorization = request.headers['authorization'].split()
    except KeyError:
        return HttpResponseForbidden('missing authorization header')
    if len(authorization) != 2 or authorization[0] != 'Bearer':
        return HttpResponseForbidden('invalid authorization header')
    try:
        access_token = OAuthAccessToken.objects.get(token=authorization[1])
    except OAuthAccessToken.DoesNotExist:
        return HttpResponseForbidden('missing access token')

    sub = OAuthSub.objects.get(client=access_token.client, user=access_token.user)

    user_info = {
        # use a random string as id, as it is required for pharum not to pick
        # an existing and wrong user.
        'id': str(random.randint(10**6, 10**7)),
        'email': access_token.user.email,
        'name': str(access_token.user),
        'username': slugify(str(access_token.user)),
        'sub': sub.sub,
    }
    return JsonResponse(user_info)


def jwks(request):
    return JsonResponse({'keys': []})


def well_known_openid_configuration(request):
    data = {
        'issuer': request.build_absolute_uri('/'),
        'authorization_endpoint': request.build_absolute_uri(reverse('oauth-authorize')),
        'token_endpoint': request.build_absolute_uri(reverse('oauth-token')),
        'jwks_uri': request.build_absolute_uri(reverse('oauth-jwks')),
        'userinfo_endpoint': request.build_absolute_uri(reverse('oauth-user-info')),
        'token_endpoint_auth_methods_supported': ['client_secret_post'],
    }
    return JsonResponse(data)

panikdb/pige/views.py
import datetime
from functools import partial

from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseNotAllowed, HttpResponseRedirect, StreamingHttpResponse
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .models import PigeRequest
from .utils import create_process_from_spec, is_internal


class PigeDownloadMixin:
    def get_pige_context_data(self):
        context = {}
        if settings.PIGES:
            context['pige_minimum_date'] = datetime.datetime.now() - datetime.timedelta(days=100)
            context['pige_hours'] = ['%02d' % x for x in range(24)]
            context['pige_minutes'] = ['%02d' % x for x in range(0, 60, 15)]
        return context


def download(request, *args, **kwargs):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    # studio2-20160515-13h45-14h00m05.flac
    name = '%(src)s-%(date)s-%(start_hour)sh%(start_min)s-%(end_hour)sh%(end_min)s' % {
        'src': request.POST['src'],
        'date': request.POST['date'].replace('-', ''),
        'start_hour': request.POST['start_hour'],
        'start_min': request.POST['start_min'],
        'end_hour': request.POST['end_hour'],
        'end_min': request.POST['end_min'],
    }
    if is_internal(request):
        name = name + '.wav'
    else:
        name = name + '.ogg'
    if 'sendmail' in request.POST:
        email = request.POST['email']
        PigeRequest.objects.create(email=email, download_spec=name, mode='sendmail')
        messages.info(
            request,
            _(
                'An email with a download link will soon be sent to %s, '
                'please be patient, it may take up to 20 minutes to arrive.'
            )
            % email,
        )
        return HttpResponseRedirect(reverse('regie-home'))
    else:  # direct download
        return HttpResponseRedirect(reverse('pige-download-spec', kwargs={'spec': name}))


def download_spec(request, spec, *args, **kwargs):
    proc = create_process_from_spec(spec)
    if spec.endswith('.wav'):
        content_type = 'audio/x-wav'
    else:
        content_type = 'audio/ogg'
    response = StreamingHttpResponse(iter(partial(proc.stdout.read, 500_000), b''), content_type=content_type)
    response['Content-Disposition'] = f'attachment; filename={spec}'
    return response


def download_pending(request, *args, **kwargs):
    pass

panikdb/service_messages/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.views.generic.edit import UpdateView

from .models import Message


class MessageEditView(UpdateView):
    model = Message
    fields = ['style', 'text']
    success_url = '/'
    template_name = 'service_message_form.html'

    def dispatch(self, *args, **kwargs):
        if not self.request.user.has_perm('service_messages.change_message'):
            raise PermissionDenied()
        return super().dispatch(*args, **kwargs)


message_edit = login_required(MessageEditView.as_view())

panikdb/templates/base.html
{% extends "gadjo/base.html" %}
{% load gadjo i18n panikdbtags %}
{% block page-title %}{{site_title}}{% endblock %}

{% block bodyargs %}data-no-moving-header="x"{%endblock %}

{% block gadjo-js %}
  {{ block.super }}
  <script src="/static/js/jquery.fileupload.js"></script>
  <script src="/static/js/jquery.iframe-transport.js"></script>
  <script src="/static/js/qommon.fileupload.js"></script>
  <script src="/static/js/panikdb.js"></script>
  <script type="text/javascript" src="{% xstatic "select2.js" "select2.min.js" %}"></script>
{% endblock %}

{% block css %}
  {{ block.super }}
  <link href="{% xstatic "select2.css" "select2.min.css" %}" rel="stylesheet">
  <link rel="icon" href="/static/images/favicon-16.png" type="image/png" sizes="16x16">
  <link rel="icon" href="/static/images/favicon-32.png" type="image/png" sizes="32x32">
  <link rel="icon" href="/static/images/favicon-48.png" type="image/png" sizes="48x48">
  <link rel="apple-touch-icon" href="/static/images/favicon-512.png">
{% endblock %}

{% block sidepage %}
{% endblock %}

{% block site-header %}
  <h1><a href="/">{% block site-title %}{{ site_title }}{% endblock %}</a></h1>
  {% block subheader %}
    <div id="search">
      {% if request.user.id %}
        <form class="gadjo-popup-ignore" action="{% url 'panikdb-search' %}"
              data-wiki-search-base-url="{{ wiki_search_base_url }}">
          <input type="search" name="q" placeholder="Rechercher"/>
          <button class="icon-search"></button>
        </form>
        <div id="search-results">
        </div>
      {% endif %}
    </div>
  {% endblock %}
{% endblock %}

{% block more-user-links %}
  {% block breadcrumb-links %}
    <a href="{% url 'home' %}" class="button icon-home-space">{% trans "Home" %}</a>
  {% endblock %}
{% endblock %}

{% block user-links %}
  {% if request.user.is_authenticated %}
    <a class="icon-user-space" href="{% url 'profile-view' %}">{{ request.user.first_name }} {{ request.user.last_name }} ({{ request.user.username }})</a>
    <a class="icon-signout" href="{% url 'logout' %}">{% trans "Logout" %}</a>
  {% endif %}
{% endblock %}

{% block page-end %}
  <script>
    $(document).ready(function() {
      $('select[multiple=multiple]').select2();
      $('select[multiple=multiple]').next('.helptext').hide();
      $('select#id_emission').select2();
      $('select#id_category').select2();
    });
  </script>
{% endblock %}

{% block footer %}
{% endblock %}

panikdb/templates/service_message_form.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="buttons">
      <button>{% trans "Save" %}</button>
      <a class="cancel" href="../..">{% trans "Cancel" %}</a>
    </div>
  </form>
  <script src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>

{% endblock %}

panikdb/templates/system.html
{% extends "base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% trans "System Information" %}</h2>
{% endblock %}

{% block content %}
  <div class="section">
    <h3>{% trans "Versions" %}</h3>
    <ul>
      {% for dist in pkg_resources_set %}
        <li>{{ dist.project_name }} : {{ dist.version }}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

panikdb/templates/vote.html
{% extends "base.html" %}

{% block content %}

  <h2>Bienvenue sur le sondage Logo de Radio Panik !</h2>

  <p>
    Ci-dessous, vous trouverez les deux propositions de logos préparées par
    notre graphiste embauché et validés par le Groupe LOGO.
  </p>

  <p>
    Votez pour l'un de ces logos !
  </p>

  <p>
    Vous avez aussi la possibilité de faire un commentaire pour justifier votre
    choix ou suggérer une amélioration au logo qui a votre faveur (en effet, un
    dernier travail avec le graphiste est prévu pour peaufiner le logo
    démocratiquement choisi).
  </p>

  <p>
    Vous pouvez également vous abstenir, c'est-à-dire que vous ne vous prononcez
    pas pour l'un des logos proposés mais vous devez alors justifier votre
    abstention en complétant la case « commentaire ».
  </p>

  <p>
    Vous n'avez qu¹une seule voix par identifiant, tout vote est définitif et
    vous devez voter avant le <strong>LUNDI 18 AVRIL 2016</strong>.
  </p>

  <p>
    Merci pour votre participation !
  </p>

  <hr/>

  <form method="post" class="poll">

    <div class="error" style="display: none;">
      Oups ! Vous n'avez sélectionné aucun logo proposé ! Veuillez en
      choisir un.  Vous pouvez aussi vous abstenir et ne choisir aucun
      des deux logos proposés mais dans ce cas, vous devez justifier
      votre abstention en utilisant la case « COMMENTAIRES ».
    </div>

    {% csrf_token %}
    <div class="choices">
      <label><input type="radio" name="choice" value="1"><img src="/static/poll/Panik_2016_32.jpg" height="250" alt="logo 1"/></input></label>
      <label><input type="radio" name="choice" value="2"><img src="/static/poll/Panik_2016_33.jpg" height="250" alt="logo 2"/></input></label>
      <label><input type="radio" name="choice" value="3">Abstention</input></label>
    </div>

    <p>
      Commentaire :
    </p>
    <textarea name="comment">
    </textarea>

    <div class="buttons">
      <button>Enregistrer mon vote</button>
    </div>
  </form>

  <script>
    $('form').on('submit', function() {
      var comment = $('textarea').val();
      var choice = $('input[name=choice]:checked').val();
      if (choice === undefined || (choice == "3" && comment.length < 10)) {
        $('div.error').show();
        return false;
      }
    });
  </script>

{% endblock %}

panikdb/templates/vote_results.html
{% extends "base.html" %}

{% block content %}

  <h2>Résultats</h2>

  {% for vote in object_list %}
    <div style="padding: 1ex; border-bottom: 1px solid #888;">
      {% if vote.choice == "1" %}<img src="/static/poll/Panik_2016_32.jpg" height="250" alt="logo 1"/>{% endif %}
      {% if vote.choice == "2" %}<img src="/static/poll/Panik_2016_33.jpg" height="250" alt="logo 1"/>{% endif %}
      {% if vote.choice == "3" %}<div style="display: table-cell; vertical-align: middle; height: 250px;">Abstention</div>{% endif %}

      {% if vote.comment %}
 <pre style="margin-top: 1em; font-family: sans-serif;">{{vote.comment}}</pre>
      {% endif %}
    </div>
  {% endfor %}

  <div style="border-top: 1px solid #888; padding: 1ex;">
    Totaux :
    <ul>
      <li>1: {{choice_1}}</li>
      <li>2: {{choice_2}}</li>
      <li>3: {{choice_3}}</li>
    </ul>
  </div>



{% endblock %}